#Filter
#이벤트가 특정 조건에 부합할 때 실행
#워크플로우 실행을 더 효과적으로 제어
#branch, path, tag

#특정 branch에서 실행
#ex) dev, master branch 중에서 master branch로 push해야만 실행
#특정 path에서 실행
#특정 tag에서 실행


name: branch-filter
on:
  push:
    branches: ["dev"] #이렇게 하면 dev에서 이벤트가 발생했을 때만 작동하게 된다.branches-ignore:

jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello
