#if: always() - 특정 job과 step을 강제로 실행 가능

name: if-2
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: exit 1
        run: exit 1
      - name: echo
        if: always() #이렇게 되면 echo도 실행된다.
        run: echo hello

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    if: always() #always()로 인해 job2가 실행된다.
    steps:
      - name: echo
        run: echo hello