#secret
#민감한 데이터를 안전하게 저장해서 워크플로우에서 사용
#민감 정보를 코드와 분리하여, 노출되는 것 방지
#ex) API Key, 암호, 인증 토큰

#안전한 저장 - 깃헙에서 안전하게 암호화
#로깅 방지 - 로그에 기록되지 않고, 출력 시 마스킹
#접근 제한 - 워크플로우 실행 중에만 접근 가능

#정의된 시크릿을 바꾸면 워크플로우 결과 달라질 수 있음

#secret값은 깃허브 홈페이지에서 세팅할 수 있다.

name: secrets
on: push

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: get secrets
        run: echo ${{ secrets.level }}
