name: string-function
on: push

jobs:
  string-function:
    runs-on: ubuntu-latest
    steps:
      - name: startswith
        if: startsWith('github actions', 'git')
        run: echo "git" #true
      - name: startswith
        if: startsWith('github actions', 'test')
        run: echo "test" #false

      - name: endswith
        if: endsWith('github actions', 'ions')
        run: echo "ions" #true
      - name: endsWith
        if: endsWith('github actions', 'test')
        run: echo "test" #false

      - name: contains
        if: contains('github actions', 'act')
        run: echo "contains act" #true
      - name: contains
        if: contains('github, actions', 'git)
        run: echo "contains git" #true