#tag filter
#특정 태그에서 실행
#ex) v1.0.0으로 태깅해야 실행
#push event에서만 사용 가능
#태그를 사용하는 방법 git tag <tag-name>

name: tag-filter
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' #v1.0.0 or v2.2.2

jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello
