#environment variables
#step이나 job에서 사용할 수 있는 환경 변수
#key-value형태로 데이터 저장

#output - 같은 job, 다른 job 간에 데이터 공유
#env - 동일한 job에서만 데이터 공유
#워크플로우 내에서 정의

#workflow level
#job level
#step level

name: var-1
on: push

env:
  level: workflow

jobs:
  get-env-1:
    runs-on: ubuntu-latest
    steps:
      - name: check env
        run: echo "LEVEL ${{ env.level }}"

  get-env-2:
    runs-on: ubuntu-latest
    env:
      level: job
    steps:
      - name: check env
        run: echo "LEVEL ${{ env.level }}"

